# HarborList Local Application Services
# This file contains all application services that depend on infrastructure being ready
# Infrastructure MUST be started first with docker-compose.infrastructure.yml
# Usage: docker-compose -f docker-compose.application.yml up -d

services:
  # Traefik Reverse Proxy
  traefik:
    image: traefik:v3.0
    container_name: harborlist-app-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--accesslog=true"
      - "--log.level=INFO"
      - "--serversTransport.insecureSkipVerify=true"
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-config:/etc/traefik/dynamic:ro
      - ./certs/local:/etc/ssl/certs:ro
    networks:
      - harborlist-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-http.rule=Host(`traefik.local.harborlist.com`)"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.middlewares=https-redirect@file"
      - "traefik.http.routers.dashboard-https.rule=Host(`traefik.local.harborlist.com`)"
      - "traefik.http.routers.dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.dashboard-https.tls=true"
      - "traefik.http.routers.dashboard-https.service=api@internal"

  # Frontend development server
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: harborlist-app-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/frontend/node_modules
      - /workspace/packages/shared-types/node_modules
    environment:
      - VITE_API_URL=https://local-api.harborlist.com/api
      - VITE_ENVIRONMENT=local
      - CHOKIDAR_USEPOLLING=true
    networks:
      - harborlist-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.rule=Host(`local.harborlist.com`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=https-redirect@file"
      - "traefik.http.routers.frontend-https.rule=Host(`local.harborlist.com`)"
      - "traefik.http.routers.frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frontend-https.tls=true"
      - "traefik.http.routers.frontend-https.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.services.frontend.loadbalancer.server.scheme=http"

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      target: backend
    container_name: harborlist-app-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/backend/node_modules
      - /workspace/packages/shared-types/node_modules
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=local
      - DEPLOYMENT_TARGET=docker
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - S3_ENDPOINT=http://localstack:4566
      - SES_ENDPOINT=http://localstack:4566
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - SMTP_SECURE=false
      - ACCESS_TOKEN_EXPIRY_SECONDS=86400
      - FROM_EMAIL=noreply@harborlist.local
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - CORS_ORIGINS=https://local.harborlist.com,http://localhost:3000
      - API_BASE_URL=https://local-api.harborlist.com
      - FRONTEND_URL=https://local.harborlist.com
      - LISTINGS_TABLE=harborlist-listings
      - USERS_TABLE=harborlist-users
      - MEDIA_BUCKET=harborlist-media-local
      - THUMBNAILS_BUCKET=harborlist-thumbnails-local
      - REVIEWS_TABLE=harborlist-reviews
      - SESSIONS_TABLE=harborlist-sessions
      - LOGIN_ATTEMPTS_TABLE=harborlist-login-attempts
      - AUDIT_LOGS_TABLE=harborlist-audit-logs
      - COGNITO_ENDPOINT=http://localstack:4566
      - IS_LOCALSTACK=true
      # Customer User Pool Configuration (from .env.local)
      - CUSTOMER_USER_POOL_ID=${CUSTOMER_USER_POOL_ID}
      - CUSTOMER_USER_POOL_CLIENT_ID=${CUSTOMER_USER_POOL_CLIENT_ID}
      - CUSTOMER_USER_POOL_REGION=us-east-1
      # Staff User Pool Configuration (from .env.local)
      - STAFF_USER_POOL_ID=${STAFF_USER_POOL_ID}
      - STAFF_USER_POOL_CLIENT_ID=${STAFF_USER_POOL_CLIENT_ID}
      - STAFF_USER_POOL_REGION=us-east-1
      # Auth Service Configuration
      - AUTH_SERVICE_ENDPOINT=http://backend:3001/auth
      - CUSTOMER_AUTH_ENDPOINT=http://backend:3001/auth/customer
      - STAFF_AUTH_ENDPOINT=http://backend:3001/auth/staff
      - CUSTOMER_TOKEN_TTL=86400
      - STAFF_TOKEN_TTL=28800
      - JWT_ALGORITHM=RS256
      # Enhanced feature tables
      - ENGINES_TABLE=harborlist-engines
      - BILLING_ACCOUNTS_TABLE=harborlist-billing-accounts
      - TRANSACTIONS_TABLE=harborlist-transactions
      - FINANCE_CALCULATIONS_TABLE=harborlist-finance-calculations
      - MODERATION_QUEUE_TABLE=harborlist-moderation-queue
      - USER_GROUPS_TABLE=harborlist-user-groups
      # Payment processor configuration
      - STRIPE_SECRET_KEY=sk_test_local_development_key
      - STRIPE_WEBHOOK_SECRET=whsec_local_development_secret
      - PAYPAL_CLIENT_ID=local_paypal_client_id
      - PAYPAL_CLIENT_SECRET=local_paypal_client_secret
      - PAYMENT_PROCESSOR=stripe
    networks:
      - harborlist-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-http.rule=Host(`local-api.harborlist.com`)"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.middlewares=https-redirect@file"
      - "traefik.http.routers.backend-https.rule=Host(`local-api.harborlist.com`)"
      - "traefik.http.routers.backend-https.entrypoints=websecure"
      - "traefik.http.routers.backend-https.tls=true"
      - "traefik.http.routers.backend-https.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"
      - "traefik.http.services.backend.loadbalancer.server.scheme=http"

  # Billing Service
  billing-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      target: billing-service
    container_name: harborlist-app-billing
    ports:
      - "3002:3002"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/backend/node_modules
      - /workspace/packages/shared-types/node_modules
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=local
      - DEPLOYMENT_TARGET=docker
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - JWT_SECRET=local-dev-secret-harborlist-2025
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - CORS_ORIGINS=https://local.harborlist.com,http://localhost:3000
      - API_BASE_URL=https://local-api.harborlist.com
      - FRONTEND_URL=https://local.harborlist.com
      - USERS_TABLE=harborlist-users
      - BILLING_ACCOUNTS_TABLE=harborlist-billing-accounts
      - TRANSACTIONS_TABLE=harborlist-transactions
      - AUDIT_LOGS_TABLE=harborlist-audit-logs
      - STRIPE_SECRET_KEY=sk_test_local_development_key
      - STRIPE_WEBHOOK_SECRET=whsec_local_development_secret
      - PAYPAL_CLIENT_ID=local_paypal_client_id
      - PAYPAL_CLIENT_SECRET=local_paypal_client_secret
      - PAYMENT_PROCESSOR=stripe
      - SERVICE_PORT=3002
      - COGNITO_ENDPOINT=http://localstack:4566
      - IS_LOCALSTACK=true
      - CUSTOMER_USER_POOL_ID=${CUSTOMER_USER_POOL_ID}
      - CUSTOMER_USER_POOL_CLIENT_ID=${CUSTOMER_USER_POOL_CLIENT_ID}
      - STAFF_USER_POOL_ID=${STAFF_USER_POOL_ID}
      - STAFF_USER_POOL_CLIENT_ID=${STAFF_USER_POOL_CLIENT_ID}
    networks:
      - harborlist-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.billing-http.rule=Host(`billing.local.harborlist.com`)"
      - "traefik.http.routers.billing-http.entrypoints=web"
      - "traefik.http.routers.billing-http.middlewares=https-redirect@file"
      - "traefik.http.routers.billing-https.rule=Host(`billing.local.harborlist.com`)"
      - "traefik.http.routers.billing-https.entrypoints=websecure"
      - "traefik.http.routers.billing-https.tls=true"
      - "traefik.http.routers.billing-https.service=billing-service"
      - "traefik.http.services.billing-service.loadbalancer.server.port=3002"
      - "traefik.http.services.billing-service.loadbalancer.server.scheme=http"

  # Finance Service
  finance-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      target: finance-service
    container_name: harborlist-app-finance
    ports:
      - "3003:3003"
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/backend/node_modules
      - /workspace/packages/shared-types/node_modules
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=local
      - DEPLOYMENT_TARGET=docker
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - JWT_SECRET=local-dev-secret-harborlist-2025
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - CORS_ORIGINS=https://local.harborlist.com,http://localhost:3000
      - API_BASE_URL=https://local-api.harborlist.com
      - FRONTEND_URL=https://local.harborlist.com
      - LISTINGS_TABLE=harborlist-listings
      - USERS_TABLE=harborlist-users
      - FINANCE_CALCULATIONS_TABLE=harborlist-finance-calculations
      - SERVICE_PORT=3003
      - COGNITO_ENDPOINT=http://localstack:4566
      - IS_LOCALSTACK=true
      - CUSTOMER_USER_POOL_ID=${CUSTOMER_USER_POOL_ID}
      - CUSTOMER_USER_POOL_CLIENT_ID=${CUSTOMER_USER_POOL_CLIENT_ID}
      - STAFF_USER_POOL_ID=${STAFF_USER_POOL_ID}
      - STAFF_USER_POOL_CLIENT_ID=${STAFF_USER_POOL_CLIENT_ID}
    networks:
      - harborlist-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finance-http.rule=Host(`finance.local.harborlist.com`)"
      - "traefik.http.routers.finance-http.entrypoints=web"
      - "traefik.http.routers.finance-http.middlewares=https-redirect@file"
      - "traefik.http.routers.finance-https.rule=Host(`finance.local.harborlist.com`)"
      - "traefik.http.routers.finance-https.entrypoints=websecure"
      - "traefik.http.routers.finance-https.tls=true"
      - "traefik.http.routers.finance-https.service=finance-service"
      - "traefik.http.services.finance-service.loadbalancer.server.port=3003"
      - "traefik.http.services.finance-service.loadbalancer.server.scheme=http"

  # SMTP4Dev for local email testing
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: harborlist-app-smtp
    ports:
      - "5001:80"
      - "2525:25"
    environment:
      - ServerOptions__HostName=smtp4dev
    networks:
      - harborlist-local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smtp4dev-http.rule=Host(`mail.local.harborlist.com`)"
      - "traefik.http.routers.smtp4dev-http.entrypoints=web"
      - "traefik.http.routers.smtp4dev-http.middlewares=https-redirect@file"
      - "traefik.http.routers.smtp4dev-https.rule=Host(`mail.local.harborlist.com`)"
      - "traefik.http.routers.smtp4dev-https.entrypoints=websecure"
      - "traefik.http.routers.smtp4dev-https.tls=true"
      - "traefik.http.routers.smtp4dev-https.service=smtp4dev"
      - "traefik.http.services.smtp4dev.loadbalancer.server.port=80"
      - "traefik.http.services.smtp4dev.loadbalancer.server.scheme=http"

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: harborlist-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - harborlist-local

volumes:
  redis_data:
    name: harborlist-redis-data

networks:
  harborlist-local:
    external: true
    name: harborlist-local-network
