# Traefik Dynamic Configuration
# SSL certificates and advanced routing rules

tls:
  certificates:
    - certFile: /etc/ssl/certs/server-cert.pem
      keyFile: /etc/ssl/certs/server-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/certs/server-cert.pem
        keyFile: /etc/ssl/certs/server-key.pem

http:
  middlewares:
    # WAF-like security middleware
    security-waf:
      plugin:
        block-malicious:
          enabled: true
          rules:
            - "(?i)(union|select|insert|delete|drop|create|alter)"
            - "(?i)(<script|javascript:|vbscript:|onload=|onerror=)"
            - "(?i)(\\.\\.[\\/\\\\]|\\.\\.%)"
    
    # Rate limiting tiers
    api-auth-rate:
      rateLimit:
        burst: 10
        average: 1
        sourceCriterion:
          requestHeaderName: "Authorization"
    
    public-api-rate:
      rateLimit:
        burst: 50
        average: 5
        sourceCriterion:
          ipStrategy:
            depth: 1
    
    admin-api-rate:
      rateLimit:
        burst: 20
        average: 2
        sourceCriterion:
          requestHeaderName: "Authorization"
    
    # Compression (like Cloudflare)
    compression:
      compress: 
        excludedContentTypes:
          - "text/event-stream"
    
    # HTTPS redirect
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    
    # Custom error pages
    error-pages:
      errors:
        status: 
          - "404"
          - "500"
          - "503"
        service: "error-page-service"
        query: "/{status}.html"

  # Routes and services are defined via Docker Compose labels
  # This file only contains middlewares for reuse